# Generated by Django 2.2.6 on 2019-10-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_announcement_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
